name: MCEngineArtificialIntelligence
version: ${version}
main: io.github.mcengine.spigotmc.artificialintelligence.engine.MCEngineArtificialIntelligenceSpigotMC
author: MCEngine
description: MCEngine Artificial Intelligence
api-version: 1.18
commands:
  ai:
    description: Get AI response
    usage: /<command>
    permission: mcengine.artificialintelligence.use
    permission-message: You do not have permission to use this command.

permissions:
  mcengine.artificialintelligence.*:
    description: Gives access to all AI commands
    children:
      mcengine.artificialintelligence.use: true
      mcengine.artificialintelligence.reload: true

  mcengine.artificialintelligence.use:
    description: Allows the player to start an AI conversation
    default: op

  mcengine.artificialintelligence.reload:
    description: Allows the player to reload the AI plugin
    default: op
